source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'Date_Tests', :exclusive => true do
  pod 'Date', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'master'
end
